#echo "Hello from .bash_profile"
source "$HOME/.config/bash/shell"
source "$HOME/.config/bash/commands"
source "$HOME/.config/bash/colors"
source "$HOME/.config/bash/prompt"
source "$HOME/.config/bash/aliases"
