#!/bin/bash

# apt-get and aptitude
alias upandup='sudo apt update && sudo apt upgrade -y'
alias install='sudo apt install'
alias remove='sudo apt remove'
alias autoremove='sudo apt autoremove'
alias search='sudo apt-cache search'

# ViM
alias v='vim'
alias sv='svim'
alias svim='sudoedit'
alias note='vim "$(date +"%A, %B %e %Y")".md'

# Add a path to the env variable passed to sudo
alias sudo='sudo env "PATH=$PATH"'

# Git
alias gl='git log --color --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue) <%an> %Creset" --abbrev-commit'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gs='git status'

# Directory related shortcuts
alias ..='cd ..'
alias mkdir='mkdir -pv'
alias ls='ls -a --color=auto'
alias la='ls -alh'

# Safety Checks (aka, always prompt for confirmation)
alias mv='mv -i -v'
alias cp='cp -i -v'
alias ln='ln -i -v'
alias rm='rm -I -v'

# Make mount output prettier
alias mountt='mount | column -t'
