#!/bin/bash

#### Prompt Configuration File ####

#Set username color based on who is logged in
if [ $USER == "coleman" ]; then
	USER_COLOR=$FG_CYAN
elif [ $USER == "root" ]; then
	USER_COLOR=$FG_RED
fi

#Set hostname color based on which host is connected
if [ $HOSTNAME == "cobalt" ]; then
	HOST_COLOR=$FG_BLUE
elif [ $HOSTNAME == "coleman-tower" ]; then
	HOST_COLOR=$FG_CYAN
elif [ $HOSTNAME == "coleman-laptop" ]; then
	HOST_COLOR=$FG_GREEN
elif [ $HOSTNAME == "hydrogen" ]; then
	HOST_COLOR=$FG_YELLOW
elif [ $HOSTNAME == "imac" ]; then
	HOST_COLOR=$FG_PURPLE
elif [ $HOSTNAME == "monitor" ]; then
	HOST_COLOR=$FG_RED
fi

#Combine the various parts of the prompt
PS1="$USER_COLOR\u$FG_DEFAULT@$HOST_COLOR\h$FG_DEFAULT $FG_PURPLE\w$FG_DEFAULT \$ "

#Export the ps1 variable
export PS1
