#!/bin/bash
# A simple plaintext summary of the network usage 
convert="/home/coleman/scripts/network/humanreadable"
echo "~~~~~ Local Network ~~~~~"
echo "Sent: " $(cat /sys/class/net/br0/statistics/tx_bytes | $convert)
echo "Recieved: "$(cat /sys/class/net/br0/statistics/rx_bytes | $convert)
echo
echo "~~~~~ Outgoing Traffic ~~~~~"
echo "Sent: "$(cat /sys/class/net/eth1/statistics/tx_bytes | $convert)
echo "Recieved: "$(cat /sys/class/net/eth1/statistics/rx_bytes | $convert)
