#!/bin/bash
#A simple script to forward ports through iptables NAT
echo -n "Enter the external port: "
read extport
echo -n "Enter the client you would like to forward to: "
read client
echo -n "Emter the internal port: "
read inport
echo -n "Which protocol would you like to use (tcp, udp, both): "
read protocol
echo
sudo iptables -t nat -A PREROUTING -i eth1 -p $protocol --dport $extport -j DNAT --to $client:$inport
sudo iptables -A fw-open -d $client -p $protocol --dport $inport -j ACCEPT

