#!/bin/bash

# apt-get and aptitude
alias upandup='sudo apt update && sudo apt upgrade -y'
alias install='sudo apt install'
alias remove='sudo apt remove'
alias autoremove='sudo apt-get autoremove'
alias search='sudo apt-cache search'

# ViM
alias v='vim'
alias vf='v $(fzf)'
alias sv='svim'
alias svim='sudoedit'
alias note='vim "$(date +"%A, %B %e %Y")".md'

# Git
alias gl='git log --color --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue) <%an %GK> %Creset" --abbrev-commit'
alias ga='git add'
alias gc='git commit --verbose'
alias gd='git diff'
alias gs='git status'

# Docker
alias d='docker'
alias db='docker build'
alias de='docker exec -it'
alias dp='docker pull'
alias dspa='docker system prune -a'
alias dc='docker-compose'
alias dcb='dc build'
alias dcu='dc up'

# Directory related shortcuts
alias ..='cd ..'
alias mkdir='mkdir -pv'
alias ls='ls -a --color=auto'
alias la='ls -alh'
alias l='la'

# Safety Checks (aka, always prompt for confirmation)
alias mv='mv -i -v'
alias cp='cp -i -v'
alias ln='ln -i -v'
alias rm='rm -I -v'

# Make mount output prettier
alias mountt='mount | column -t'

# Force Mutt to use the correct config file
alias mutt='mutt -F ~/.config/mutt/muttrc'

# Force ncmpcpp to use sane bindings
alias ncmpcpp='ncmpcpp -b .config/ncmpcpp/bindings'

# Make viewing tasks with Taskwarrior easier
alias work='task project:work'
alias school='task project:school'
alias personal='task project:personal'
