#!/bin/bash

#### Color configuration file ####

## Special ##
FG_DEFAULT='\[$(tput sgr0)\]'

## Foreground ##
FG_BLACK='\[$(tput setaf 0)\]'
FG_RED='\[$(tput setaf 1)\]'
FG_GREEN='\[$(tput setaf 2)\]'
FG_YELLOW='\[$(tput setaf 3)\]'
FG_BLUE='\[$(tput setaf 4)\]'
FG_PURPLE='\[$(tput setaf 5)\]'
FG_CYAN='\[$(tput setaf 6)\]'
FG_WHITE='\[$(tput setaf 7)\]'

## Background ##
BG_BLACK='\ [$(tput setab 0)\]'
BG_RED='\[$(tput setab 1)\]'
BG_GREEN='\[$(tput setab 2)\]'
BG_YELLOW='\[$(tput setab 3)\]'
BG_BLUE='\[$(tput setab 4)\]'
BG_PURPLE='\[$(tput setab 5)\]'
BG_CYAN='\[$(tput setab 6)\]'
BG_WHITE='\[$(tput setab 7)\]'

## Bold ##
BOLD='\[$(tput bold)\]'

## Underline ##
S_UL='\[$(tput smul)\]'
E_UL='\[$(tput rmul)\]'
