#!/bin/bash
function whereami {
	echo "You are logged in as $USER_COLOR$USER$FG_DEFAULT on $HOST_COLOR$HOSTNAME$FG_DEFAULT"
	echo "You are using the Bash Shell version $BASH_VERSION"
	echo "You are currently in the directory $FG_BLUE$PWD$FG_DEFAULT"
	echo "Your home directory is currently set to $FG_BLUE$HOME$FG_DEFAULT"
	return 0
}

function stripurlsfromhtml {
	 grep -Po '(?<=href=")[^"]*' $1
}

# See http://askubuntu.com/questions/27314/script-to-display-all-terminal-colors for details
function colortest {
	for x in 0 1 4 5 7 8; do 
		for i in {30..37}; do 
			for a in {40..47}; do 
				echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m ";
		       	done;
			echo; 
		done; 
	done; 
	echo "";
}

# Render notes taken in markdown to HTML and include a style file for some basic styling
function rendernotes {
	cat styles.md > $1.html
	markdown $1.md >> $1.html
}

# Toggle the $lb variable which controls whether or not the prompt will be on another line
function lb {
	if [ "$lb" == "true" ]; then
		export lb="false"
	else
		export lb="true"
	fi
}
