#!/bin/bash

# Set username color based on who is logged in
if [ "$USER" == "coleman" ]; then
	USER_COLOR=$FG_CYAN
elif [ "$USER" == "root" ]; then
	USER_COLOR=$FG_RED
fi

# Set hostname color based on which host is connected
if [ "$HOSTNAME" == "cobalt" ]; then
	HOST_COLOR=$FG_BLUE
elif [ "$HOSTNAME" == "coleman-tower" ]; then
	HOST_COLOR=$FG_CYAN
elif [ "$HOSTNAME" == "coleman-laptop" ]; then
	HOST_COLOR=$FG_GREEN
elif [ "$HOSTNAME" == "hydrogen" ]; then
	HOST_COLOR=$FG_YELLOW
elif [ "$HOSTNAME" == "nickel" ]; then
	HOST_COLOR=$FG_PURPLE
elif [ "$HOSTNAME" == "copper" ]; then
	HOST_COLOR=$FG_RED
fi

# Export prompt_command
export PROMPT_COMMAND="source ~/.config/bash/prompt_command"

# Attach tmux if started and the shell is interactive, create one if not
# FIXME: Currently, this is non-functional
if [ "$-" == "*i*" ]; then
	if [ -z "$TMUX" ]; then
		tmux attach
		if [ "$?" -ne 0 ]; then
			tmux new -s login
		fi
	fi
fi
