#!/bin/bash

#### Shell Configuration File ####

# Set default editor to vim
export EDITOR=/usr/bin/vim
export VISUAL=$EDITOR

# Add scripts diredctory to path
if [ -d $HOME/bin/ ]; then
	export PATH=$PATH:$HOME/bin
fi

# Add colors to ls and friends
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.config/dircolors && eval "$(dircolors -b ~/.config/dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias grep='grep --color=auto' 
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# Don't put duplicate lines in the history. See bash(1) for more options or force ignoredups and ignorespace
export HISTCONTROL=ignoredups:ignorespace

# Append to the history file, don't overwrite it
shopt -s histappend

# Save history immediately rather than when the shell exits
PROMPT_COMMAND='history -a;history -n'

# Setting both of the following to -1 means unlimited for both
export HISTSIZE=-1
export HISTFILESIZE=-1

# Set the format for the history file
export HISTTIMEFORMAT='%F %T '

# Check the window size after each command and, if necessary,update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Make sure GPG knows what TTY we are using
export GPG_TTY=$(tty)
