#!/bin/bash
#### Sync various settings, files, and scripts across devices ####

## Variables ##
package_list="/home/coleman/scripts/packages.txt"

#Print various information about this script
echo "[INFO] Starting synchronization script..."

#Configure git settings
echo -n "[INFO] Setting git username and email..."
git config --global user.name "Coleman Nugent"
git config --global user.email "colemannugent@gmail.com"
echo " done!"

echo "[INFO] The rest of this script requires superuser privilidges, enter your password at the prompt." 
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

echo -n "[INFO] Installing packages"

#Check if packages are installed
while read line; do
	sudo apt-get install -y $line > /dev/null
	echo -n "."
done < $package_list

echo " done!"

#Set the default editor
update-alternatives --set editor /usr/bin/vim.basic
