#!/bin/bash

for i in {a..j}; do
	echo "/dev/sd"$i": "
	smartctl --all /dev/sd$i | grep -E 'Number|Model|SATA V'
	echo -n "Power_On_Hours: "
	smartctl --all /dev/sd$i | grep Power_On_Hours | tr -s " " " " | cut -d " " -f 11
	echo
done
